### ISSUE TITLE
requests.exceptions.ProxyError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: 

### ISSUE THREAD

**Issue by Difkyear** [lewangdev/PaddleWebOCR#15]
PS C:\Users\Administrator\Downloads\PaddleWebOCR-1.2.2> uvicorn paddlewebocr.main:app --host 0.0.0.0 --port 8080
c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
[2022/12/01 21:21:38] root WARNING: lang en is not support in PP-OCRv2, auto switch to version PP-OCR
[2022/12/01 21:21:38] root WARNING: lang chinese_cht is not support in PP-OCRv2, auto switch to version PP-OCR
[2022/12/01 21:21:38] root WARNING: version PP-OCRv2 not support cls models, auto switch to version PP-OCR
download https://paddleocr.bj.bcebos.com/dygraph_v2.0/multilingual/en_ppocr_mobile_v2.0_det_infer.tar to ./inference/ch_ppocr_mobile_v2.0_det_infer\en_ppocr_mobile_v2.0_det_infer.tar
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\urllib3\connection.py", line 505, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 499, in send
    timeout=timeout,
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\urllib3\connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /dygraph_v2.0/multilingual/en_ppocr_mobile_v2.0_det_infer.tar (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\uvicorn\main.py", line 449, in main
    h11_max_incomplete_event_size=h11_max_incomplete_event_size,
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\paddlewebocr\main.py", line 11, in <module>
    from paddlewebocr.route.api import api_router
  File ".\paddlewebocr\route\api.py", line 3, in <module>
    from paddlewebocr.route.v1 import ocr
  File ".\paddlewebocr\route\v1\ocr.py", line 8, in <module>
    from paddlewebocr.pkg.ocr import text_ocr
  File ".\paddlewebocr\pkg\ocr.py", line 12, in <module>
    use_gpu=False, total_process_num=os.cpu_count(), use_mp=True, show_log=False),
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\paddleocr\paddleocr.py", line 326, in __init__
    maybe_download(params.det_model_dir, det_url)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\paddleocr\ppocr\utils\network.py", line 55, in maybe_download
    download_with_progressbar(url, tmp_path)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\paddleocr\ppocr\utils\network.py", line 26, in download_with_progressbar
    response = requests.get(url, stream=True)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /dygraph_v2.0/multilingual/en_ppocr_mobile_v2.0_det_infer.tar (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
PS C:\Users\Administrator\Downloads\PaddleWebOCR-1.2.2>

**Comment by Difkyear** [comment]
请问一下这个怎么解决?

**Comment by Difkyear** [comment]
我不小心打开了其他代理导致的
